### PR TITLE
fix: implement issuer display properties according to spec

### LINKED ISSUE #247: Use `name` and `logo.url` for issuer metadata lookup
### Description

Currently we use `"client_name"` and `"logo_uri"` to find the `issuer_name` and `logo_uri`, like this:
```rust
                let issuer_name = display["client_name"]
                    .as_str()
                    .map(|s| s.to_string())
                    .unwrap_or(credential_issuer_url.to_string());

                let logo_uri = display["logo_uri"].as_str().map(|s| s.to_string());
```

However, this is a custom NGDIL-specific way of obtaining these display properties (see: https://staging.api.ngdil.com/.well-known/openid-credential-issuer).

The display described in OID4VCI looks like can be found here: https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-11.2.3-2.10.2.3.2.2).

The specification should be leading which means we should look for these display properties through:
```rust
{
  "name": ...,
  "logo": {
    "url": ...
  }
}
```

If UniMe can not find these display properties it may try to find it via `client_name` and `logo_uri`.

### Motivation

We should prioritize the OID4VCI specification.

### Resources

https://staging.api.ngdil.com/.well-known/openid-credential-issuer
https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-11.2.3-2.10.2.3.2.2

### To-do List

- [ ] Implement display property lookup

### PR DESCRIPTION
**Pull request by nanderstabel**
# Description of change
For more information about what this PR fixes see this [issue](https://github.com/impierce/identity-wallet/issues/247)

## Links to any relevant issues
fixes #247 

## How the change has been tested
Manually tested (see internal discussion)

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs [hunk 1]
```diff
@@ -87,24 +87,20 @@ pub async fn read_credential_offer(state: AppState, action: Action) -> Result<Ap
         // Get the credential issuer name and logo uri or use the credential issuer url.
         let (issuer_name, logo_uri) = display
             .map(|display| {
-                let issuer_name = display["client_name"]
+                let issuer_name = display["name"]
                     .as_str()
+                    // TODO(NGDIL): remove thsi NGDIL specific logic once: https://staging.api.ngdil.com/.well-known/openid-credential-issuer is fixed.
```
Comment (daniel-mader) [inline identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs]: `[resolve]`

Little typo `remove thsi` => `remove this`

File: identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs [hunk 2]
```diff
@@ -87,24 +87,20 @@ pub async fn read_credential_offer(state: AppState, action: Action) -> Result<Ap
...
-                //     .as_object()
-                //     .unwrap()
-                //     .get("url")
-                //     .unwrap()
-                //     .as_str()
-                //     .map(|s| s.to_string());
+                let logo_uri = display["logo"]
+                    .as_object()
+                    .and_then(|logo| logo["url"].as_str())
+                    // TODO(NGDIL): remove thsi NGDIL specific logic once: https://staging.api.ngdil.com/.well-known/openid-credential-issuer is fixed.
```
Comment (daniel-mader) [inline identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs]: `[resolve]`

Little typo `remove thsi` => `remove this`

**Review by daniel-mader — DISMISSED** [review]

**Review by daniel-mader — DISMISSED** [review]

**Review by daniel-mader — APPROVED** [review]

**Review by maiertech — APPROVED** [review]
Approved after code walk-through with @daniel-mader.
