### PR TITLE
fix: derive `connection_id` from `client_name` and make it non-optional

### LINKED ISSUE #150: [Bug] Not all events shown through the connection view
### Description

When you click on a connection an event is missing.

### Hardware Specification

_No response_

### Steps to Reproduce the Bug

1. Run the Shenron profile
2. click on the added connection
4. Go to the history of that connection (missing the received credential)

### Expected Behaviour

To see all history events related to that issuer

### Actual Behaviour

It misses one history event

### Errors
Connection history without the future engineer:
image (1)

Overal history (with the future engineer):
image (2)

### PR DESCRIPTION
**Pull request by Norlock**
# Description of change
Connection history didn't show all events, because some were wrongly filtered out. This also fix a bug where date wasn't correctly when receiving credentials.

## Links to any relevant issues
Fixes #150

## How the change has been tested
I clicked on the connection and looked again

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Oran-Dan — DISMISSED** [review]

File: identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs [hunk 1]
```diff
@@ -64,10 +64,7 @@ pub async fn handle_siopv2_authorization_request(mut state: AppState, _action: A
             connection.last_interacted = connection_time.clone();
         });
 
-    // TODO: This is a HORRIBLE solution to determine the connection_id by the non-unique "issuer name".
-    // It is a TEMPORARY solution and should only be used in DEMO environments,
-    // since we currently lack a unique identitfier to distinguish connections.
-    let connection_id = base64::encode_config(&client_name, base64::URL_SAFE);
```
Comment (nanderstabel) [inline identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs:70]: `handle_oid4vp_authorization_request.rs` has the same TODO message so It would be nice to replace that there as well :)

File: identity-wallet/src/state/connections/mod.rs [hunk 2]
```diff
@@ -21,3 +21,12 @@ pub struct Connection {
 
 #[typetag::serde(name = "connection")]
 impl FeatTrait for Connection {}
+
+impl Connection {
+    // TODO: This is a HORRIBLE solution to determine the connection_id by the non-unique "issuer name".
+    // It is a TEMPORARY solution and should only be used in DEMO environments,
+    // since we currently lack a unique identitfier to distinguish connections.
```
Comment (nanderstabel) [inline identity-wallet/src/state/connections/mod.rs]: I think this is a nice opportunity to replace this somewhat screamy TODO message to :
```
// TODO(ngdil): Temporary solution to support NGDIL demo, replace with different unique identifier to distinguish connection
```

File: identity-wallet/src/state/core_utils/history_event.rs [hunk 3]
```diff
@@ -14,7 +14,7 @@ pub enum EventType {
 #[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq, TS)]
 #[ts(export)]
 pub struct HistoryEvent {
-    pub connection_id: Option<String>,
+    pub connection_id: String,
```
Comment (nanderstabel) [inline identity-wallet/src/state/core_utils/history_event.rs:17]: Since this type has changed, we should also update the bindings :+1: 

Do you think there might also be some changes needed in the frontend once the binding is updated?

**Review by nanderstabel — CHANGES_REQUESTED** [review]
Nice fixes! I think it's good to adjust the PR title and description a bit so that it also reflects the second fix you made now.

Also it the code needs a `cargo fmt` :+1: 

~~The second fix fixes issue  #125 btw so you can also add that to the description :smiley:~~

File: identity-wallet/src/state/core_utils/history_event.rs (hunk 3 above)
Comment (Norlock) [reply identity-wallet/src/state/core_utils/history_event.rs:17]: No its not needed luckily

File: identity-wallet/src/state/connections/mod.rs [hunk 4]
```diff
@@ -21,3 +21,10 @@ pub struct Connection {
 
 #[typetag::serde(name = "connection")]
 impl FeatTrait for Connection {}
+
+impl Connection {
+    // TODO(ngdil): Temporary solution to support NGDIL demo, replace with different unique identifier to distinguish connection
+    pub fn create_connection_id(client_name: &str) -> String {
+        base64::encode_config(&client_name, base64::URL_SAFE)
```
Comment (nanderstabel) [inline identity-wallet/src/state/connections/mod.rs]: We now use this method for both `client_name`'s and `issuer_name`'s. To avoid confusion I think it's slightly better to go for the more generic `connection_name` as variable name her (instead of `client_name`).

**Review by nanderstabel — DISMISSED** [review]

**Review by daniel-mader — COMMENTED** [review]
Is there any code changes required to fulfill the "treat credential offers as connections"?

File: identity-wallet/src/date_utils.rs
Comment (Oran-Dan) [inline identity-wallet/src/date_utils.rs:1]: Can you explain the reasoning behind this? it seems a bit bloaty to me?
In anyway, it should be in the core_utils folder, but i don't see the use of putting this into a file all together?
a line saying chrono::Utc::now().to-rfc3339() in the code is fine too right?

File: identity-wallet/src/state/credentials/mod.rs
Comment (Oran-Dan) [inline identity-wallet/src/state/credentials/mod.rs:1]: For example here, i don't see the gain of adding a struct, impl and a new file to the codebase? 
What was wrong with the old version?

Comment (Norlock) [reply identity-wallet/src/state/credentials/mod.rs:1]: It is now used in multiple places, so to prevent inconsistencies whenever something changes, I made it a global function. Yes its a bit much too have a new file, but I think it doesn't fit in any existing file if it supposed to be a global function. 

The reason for a struct is that it implies contexts. If you have a lot of global functions without a struct you can get name conflicts quicker and you need to search for the function name. Now you can add DateUtils and then check the function you want from it. 

I will move it to core_utils :+1:

**Review by daniel-mader — DISMISSED** [review]

**Review by Oran-Dan — APPROVED** [review]

**Review by daniel-mader — APPROVED** [review]
