### PR TITLE
refactor: remove outdated code, use proper logging, fix linting issues

### LINKED ISSUE #161: chore(frontend): remove commented code, enhance DX, remove outdated feature
### Description

* remove outdated commented code
* remove unused feature: change appearance of credential (color, icon)
* add demo history to Ferris' profile
* introduce env variable to set state of dev mode expanded (currently defaults to true)
* remove unnecessary `console.log()` statements and/or replace with proper logging (`@tauri-apps/plugin-log`)

### Motivation

Enhance developer experience, increase readability

### Resources

_No response_

### To-do List

- [x] remove outdated commented code
- [x] remove unused feature: change appearance of credential (color, icon)
- [x] add demo history to Ferris' profile
- [x] introduce env variable to set state of dev mode expanded (currently defaults to true)
- [x] remove unnecessary `console.log()` statements and/or replace with proper logging (`@tauri-apps/plugin-log`)

### PR DESCRIPTION
**Pull request by daniel-mader**
# Description of change
See linked issue: #161

## Links to any relevant issues

- #161 

## How the change has been tested
- user workflows have been checked manually for regression

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: unime/src/routes/(app)/scan/utils.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { info, warn } from '@tauri-apps/plugin-log';
 export const checkScanPrerequisites = async (): Promise<boolean> => {
   return await checkPermissions()
     .then((permission: PermissionState) => {
-      info(`app has permissions to access the camera: ${res}`);
+      info(`App has permissions to access the camera: ${permission}`);
```
Comment (nanderstabel) [inline unime/src/routes/(app)/scan/utils.ts:8]: Minor suggestion...
Since you capitalized all `info` log messages, for completeness you might want to do the same for `debug` and `warn`. 

You can find them easily by searching for `` debug(` `` and `` warn(` ``.

Comment (daniel-mader) [reply unime/src/routes/(app)/scan/utils.ts:8]: I agree, I will capitalize the other log statements as well. There are some `debug` statements where it doesn't make sense, such as:
```
debug(`assetUrl: ${assetUrl}`);`
```

File: unime/src/routes/prompt/credential-offer/+page.svelte [hunk 2]
```diff
@@ -17,74 +11,22 @@
...
-    //     credentialLogoUrl = await getImageAsset('credential', true, display.logo_uri);
-    //   }
-    // });
-    $state.current_user_prompt.display.forEach(async (display, i) => {
-      if (display.logo?.url) {
-        credentialLogoUrls[i] = await getImageAsset(`credential_${i}`, true);
-      }
-    });
-  });
+  let all_offer_indices: string[] = credential_offer.credentials.map((_, i: number) => i.toString());
```
Comment (nanderstabel) [inline unime/src/routes/prompt/credential-offer/+page.svelte]: `all_offer_indices` should be a `number[]` because otherwise this error will occur:
```
04-09 12:07:38.374 15423 15533 I         : [2024-04-09][10:07:38][INFO][webview::unknown] Dispatching action: {"type":"[Credential Offer] Selected","payload":{"offer_indices":["0","1","2","3","4"]}}
04-09 12:07:38.386 15423 15423 I Tauri/Console: File: http://tauri.localhost/node_modules/.vite/deps/@tauri-apps_plugin-log.js?v=8cb7f683 - Line 111 - Msg: [2024-04-09][10:07:38][INFO][webview::unknown] Dispatching action: {"type":"[Credential Offer] Selected","payload":{"offer_indices":["0","1","2","3","4"]}}
04-09 12:07:38.391 15423 15533 E         : [2024-04-09][10:07:38][ERROR][webview::unknown] invalid args `action` for command `handle_action`: invalid type: string "0", expected usize
```

Perhaps you can also delete the `ts_rs` attribute in this Action:
```rust
#[derive(Serialize, Deserialize, Debug, TS, Clone)]
#[ts(export, export_to = "bindings/actions/CredentialOffersSelected.ts")]
pub struct CredentialOffersSelected {
    #[ts(type = "Array<string>")]     // <-- remove this line
    pub offer_indices: Vec<usize>,
}
```

And update its binding.

Comment (daniel-mader) [reply unime/src/routes/prompt/credential-offer/+page.svelte]: Thanks for catching that!

File: unime/src/hooks.server.ts [hunk 3]
```diff
@@ -1,27 +1,18 @@
...
-export const handleError: HandleServerError = async ({ error, event, status, message }) => {
+export const handleError: HandleServerError = async ({ error }) => {
   const errorId = crypto.randomUUID();
 
-  // example integration with https://sentry.io/
-  // Sentry.captureException(error, {
-  //   extra: { event, errorId, status },
-  // });
-
+  // eslint-disable-next-line no-console
```
Comment (Oran-Dan) [inline unime/src/hooks.server.ts:11]: this comment is not very clarifying for me

**Review by nanderstabel — DISMISSED** [review]

File: unime/src/hooks.server.ts (hunk 3 above)
Comment (maiertech) [reply unime/src/hooks.server.ts:11]: It's an instruction to ESLint. Turn off rule "no-console" in next line only to mute the warning.

**Review by Oran-Dan — APPROVED** [review]
Approved, don't forget about the "eslint ignore" comments, perhaps an issue for this would be good, for the next refactor.

**Review by maiertech — COMMENTED** [review]
Much cleaner. How to go about TS warnings to be discussed in separate issue.

**Review by nanderstabel — APPROVED** [review]
