### PR TITLE
fix: prevent inconsistent state in `/welcome/terms`

### LINKED ISSUE #482: Terms & conditions dialog UI can end up in inconsistent state
### Description

When you tap the terms & conditions checkbox inside the actual checkbox, the UI can end up in an inconsistent state.

### Hardware Specification

n/a

### Steps to Reproduce the Bug

1. Reset profile and start onboarding flow.
2. In Terms & Conditions and select "agree".
3. Check data ownership.
4. Tap on the actual checkbox in Terms & Conditions and agree.
5. Now The UI is in an inconsistent state as shown in the screenshot below.

### Expected Behaviour

The inner checkbox should not be active. Toggling the state should be handled by the parent.

### Errors

n/a

### PR DESCRIPTION
**Pull request by maiertech**
# Description of change

- The `Checkbox` component can now be `readonly`, which means that its state can only be set from outside.
- The terms & conditions checkbox state can now only be changed from the dialog, not from inside the `Checkbox`.
- The dialog is now portalled to `#portal` in the root layout. This fixes the jitter and the dark mode.
- The dialog close button now receives the focus to ensure that the user has to scroll through the terms.

## Links to any relevant issues

- Fixes #482.

The description of #439 has been updated since 2 issues have been fixed with this PR.

## How the change has been tested

Test with desktop dev and on device.

## Definition of Done checklist

Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: unime/src/lib/components/Checkbox.svelte [hunk 1]
```diff
@@ -7,38 +7,50 @@
 
   export let checked = false;
   export let disabled = false;
+  /** With `readonly=true`, the checkbox state can only be changed from outside the component. */
```
Comment (daniel-mader) [inline unime/src/lib/components/Checkbox.svelte]: This could be a line comment instead of a block comment. It also looks like you intended to hint the usage of the component, so it could be a good idea to follow [the official approach](https://svelte.dev/docs/svelte/faq#How-do-I-document-my-components) instead. Some components, such as `lib/components/Image.svelte` are also documented that way.

File: unime/src/routes/welcome/terms/+page.svelte [hunk 2]
```diff
@@ -9,9 +9,12 @@
   import { XBoldIcon } from '$lib/icons';
 
   const {
-    elements: { trigger, overlay, content, title, description, close },
+    elements: { trigger, overlay, content, title, description, close, portalled },
     states: { open },
-  } = createDialog();
+  } = createDialog({
+    // Portal to root layout below `div` that sets class `dark` to ensure that dark mode works.
```
Comment (daniel-mader) [inline unime/src/routes/welcome/terms/+page.svelte]: While I understand what this does, I have a bit of a hard time reading that sentence. Could you update please?

File: unime/src/routes/welcome/terms/+page.svelte [hunk 3]
```diff
@@ -80,6 +58,17 @@
           <!-- acts as <hr> -->
           <div class="my-2 h-px w-full bg-brand" />
           <p class="text-xs font-light">{$LL.ONBOARDING.TERMS.T_AND_C.FULL()}</p>
+
+          <!-- First focusable element gets the focus (close button). This forces user to scroll through terms. -->
+          <button
+            use:melt={$close}
+            aria-label="close"
+            class="text-magnum-800 hover:bg-magnum-100 focus:shadow-magnum-400 absolute right-4 top-4 inline-flex
```
Comment (daniel-mader) [inline unime/src/routes/welcome/terms/+page.svelte]: I guess the color `magnum` got in here initially from Melt UI, but we have not defined that custom color ... 😅
While we're at it, I propose an update to the button (increase click target size, change colors, remove unused classes):
```
<button
  use:melt={$close}
  aria-label="close"
  class="absolute right-1 top-1 inline-flex size-10 appearance-none
    items-center justify-center rounded-full p-1 text-slate-500
    hover:bg-slate-100"
>
  <XBoldIcon class="size-5" />
</button>
```

**Review by daniel-mader — COMMENTED** [review]
Nice work! 👍

File: unime/src/lib/components/Checkbox.svelte (hunk 1 above)
Comment (maiertech) [reply unime/src/lib/components/Checkbox.svelte]: Changed into line comment. We should decide on conherent component comments for migrated Svelte 5 component.

File: unime/src/routes/welcome/terms/+page.svelte (hunk 2 above)
Comment (maiertech) [reply unime/src/routes/welcome/terms/+page.svelte]: Comment fixed.

File: unime/src/routes/welcome/terms/+page.svelte (hunk 3 above)
Comment (maiertech) [reply unime/src/routes/welcome/terms/+page.svelte]: Close button design aligned with reject button.

**Review by daniel-mader — APPROVED** [review]

**Review by Oran-Dan — APPROVED** [review]
