### PR TITLE
fix: Remember tab when navigating back to `/me` route

### LINKED ISSUE #269: Navigating back to the `/me` route does not remember the tab
### Description

When navigating back to the `/me` route, you might end up on an unexpected tab.

### Hardware Specification

_No response_

### Steps to Reproduce the Bug

1. Navigate to `/me`.
2. Choose tab **Badges**.
3. Click on a badge.
4. Hit the back nav button, top left.
5. You are back to `/me` but in the **All** tab.

### Actual Behaviour

When navigating back to `/me`, you always end on the **All** tab.

### Expected Behaviour

The app should remember the selected tab.

### Errors

n/a

### PR DESCRIPTION
**Pull request by maiertech**
# Description of change

When navigating away from the credentials overview on `/me` route, the active tab is now stored in page state and restored when you navigate back with `history.back()`.

## Links to any relevant issues

- Fixes #269.

## How the change has been tested

Manual testing:

- Switch to a tab other than *All* and open a credential. When you navigate back, via the top navigation, the same tab should be active.
- Also test navigating to the profile and a sub-route of the profile, and then navigating back via the top navigation.
- When you navigate away from `/me` via the bottom navigation, the active tab is not preserved. This is because the navigation does not happen via `history.back()`.

## Definition of Done checklist

Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: unime/src/lib/components/molecules/navigation/Tabs.svelte [hunk 1]
```diff
@@ -1,36 +1,25 @@
 <script lang="ts">
   import { cubicInOut } from 'svelte/easing';
+  import type { Writable } from 'svelte/store';
   import { crossfade } from 'svelte/transition';
   import { twMerge } from 'tailwind-merge';
 
   import { createTabs, melt } from '@melt-ui/svelte';
 
+  // Bring your own store to make active tab availalbe outside.
```
Comment (daniel-mader) [inline unime/src/lib/components/molecules/navigation/Tabs.svelte]: Typo: `availalbe`

File: unime/src/lib/components/molecules/navigation/Tabs.svelte [hunk 2]
```diff
@@ -1,36 +1,25 @@
...
-  } = createTabs({ defaultValue: triggers[0] });
+  } = createTabs({ value });
 
   const [send, receive] = crossfade({
     duration: 250,
     easing: cubicInOut,
   });
 </script>
 
-<!--
```
Comment (daniel-mader) [inline unime/src/lib/components/molecules/navigation/Tabs.svelte]: Shouldn't we document components?

File: unime/src/routes/(app)/me/+page.svelte [hunk 3]
```diff
@@ -120,18 +116,18 @@
         <!-- TODO: feature disabled: "Add self-signed credential" -->
         <!-- <ButtonRounded label="Add" icon={PlusCircle} /> -->
       </div>
-    {:else if $state?.user_journey}
+      <!-- {:else if $state?.user_journey} -->
```
Comment (daniel-mader) [inline unime/src/routes/(app)/me/+page.svelte]: Why comment it out entirely? I know we're not using `user_journey` at the moment, but it is still part of the Ferris dev profile and can be enabled through an env variable.

File: unime/src/lib/components/molecules/navigation/Tabs.svelte (hunk 1 above)
Comment (maiertech) [reply unime/src/lib/components/molecules/navigation/Tabs.svelte]: Fixed

File: unime/src/routes/(app)/me/+page.svelte (hunk 3 above)
Comment (maiertech) [reply unime/src/routes/(app)/me/+page.svelte]: My apologies, was not aware that it is possible to run this code. Commented out to get rid of a TS error, but putting it back.

File: unime/src/lib/components/molecules/navigation/Tabs.svelte (hunk 2 above)
Comment (maiertech) [reply unime/src/lib/components/molecules/navigation/Tabs.svelte]: I added the comment back. I don't find it super useful because it does not show the types of the properties when hovering. I think it's easier to look at the prop names and their types to understand what a component does.

I think I read somewhere that Svelte 5 will improve the comment situation by leveraging JSDoc comments. Need to revisit then.

File: unime/src/lib/components/molecules/navigation/Tabs.svelte (hunk 1 above)
Comment (daniel-mader) [reply unime/src/lib/components/molecules/navigation/Tabs.svelte]: Now it's even worse: `availalble` 😂

**Comment by daniel-mader** [comment]
Screenshot 2024-07-12 at 17 47 46

I don't know if it's just on my machine, but the Tabs in "Activity" seem to be broken?

File: unime/src/lib/components/molecules/navigation/Tabs.svelte (hunk 1 above)
Comment (maiertech) [reply unime/src/lib/components/molecules/navigation/Tabs.svelte]: Jeetje!

**Comment by maiertech** [comment]
I fixed the two tabs.

**Review by daniel-mader — APPROVED** [review]

**Review by Oran-Dan — APPROVED** [review]
Looks good!
